#' Function to produce simulated clusters
#'
#' \code{GRCsim} uses the Qiu and Joe 2006 algorithm implemented in
#' \code{clusterGeneration::genRandomClust} to create simulated clusters with
#' clustering structure generated by two separate processes, one representing a
#' measured variable like membership in a cohort and another representing a
#' latent variable of interest such as disease state. This function also changes
#' some of the continuous variables generated by the simulation algorithm into
#' dichotomous categorical columns, thereby simulating mixed-type data.
#'
#' The simulated datasets generated by this function are then used to test the
#' ability of clustering algorithms in recovering the latent cluster structure
#' that is partially obscured by the measured cluster structure (e.g.,
#' clustering by cohort).
#'
#' @param nDisClust An integer of how many latent (disease state) clusters to
#' generate. Defaults to 2.
#' @param nCohortClust An integer of how many measured (cohort) clusters to
#' generate. Defaults to 2.
#' @param ncontvars An integer of how many continuous variables to generate.
#' Defaults to 2.
#' @param ncatvars An integer of how many dichotomous categorical variables to
#' generate. Defaults to 1.
#' @param DisSepVal A value between 0 and 1 reflecting the separation index
#' value for the latent disease state clusters (see
#' \code{?clusterGeneration::genRandomClust} for details).
#'

GRCsim<-function(nDisClust=2,nCohortClust=2,ncontvars=2,ncatvars=1,DisSepVal=0.3,
                 CohortSepVal=0.15,catq=0.8,nSignal=3,nNoise=0,nOutliers=0,
                 nrep=50,DisClustSizes=c(350,150),CohortClustSizes=c(300,200),
                 CDS=F,nContCDSrootvars=1,nCatCDSrootvars=1,nContCDSgenvars=2,
                 nCatCDSgenvars=2,DisClustseed=2,CohortClustseed=3,CDSrho=0.7,
                 ratiomiss=0.2,missindex=NULL,misstype="MCAR",missseed=NULL,
                 comiss=F){
  if(nDisClust!=length(DisClustSizes)|nCohortClust!=length(CohortClustSizes)){
    stop("Mismatch between numbers of observations in each cluster and number of clusters.")
  }
  if(nNoise+nSignal!=ncontvars+ncatvars){
    stop("The sum of nSignal and nNoise must equal the sum of ncontvars and ncatvars")
  }
  cl<-match.call()
  complement <- function(y, rho, x) {
    if (missing(x)) x <- rnorm(length(y)) # Optional: supply a default if `x` is not given
    # y.perp <- residuals(lm(x ~ y))
    rho*sd(x)*y + x*sd(y)*sqrt(1 - rho^2) #replace y.perp with x
  }

  binpred<-function(x,b0,b1,seed=NULL){
    if(!is.null(seed)) set.seed(seed)
    missprobpred<-1/(1+exp(-1*(b0+nadriver*b1)))
    rbinom(length(missprobpred),1,missprobpred)
  }

  set.seed(DisClustseed)
  grc.clusts<-genRandomClust(nDisClust,sepVal=DisSepVal,numNonNoisy=nSignal,numNoisy=nNoise,
                             fileName="grc.clust",numReplicate=nrep,numOutlier=nOutliers,
                             clustszind=3,clustSizes=DisClustSizes,outputDatFlag=F,outputLogFlag=F,outputInfo=F)
  set.seed(CohortClustseed)
  grc.cohorts<-genRandomClust(nCohortClust,sepVal=CohortSepVal,numNonNoisy=nSignal,numNoisy=nNoise,
                              fileName="grc.cohort",numReplicate=nrep,numOutlier=nOutliers,
                              clustszind=3,clustSizes=CohortClustSizes,outputDatFlag=F,
                              outputLogFlag=F,outputInfo=F)
  combclusts<-list()
  if(CDS){
    for(i in 1:length(grc.clusts$datList)){
      combclusts[[i]]<-grc.clusts$datList[[i]]+grc.cohorts$datList[[i]]
      newseedstart<-DisClustseed+CohortClustseed*100
      contCDS<-matrix(0,nrow(grc.clusts$datList[[i]]),nContCDSgenvars*nContCDSrootvars)
      for(j in 1:nContCDSrootvars){
        for(k in 1:nContCDSgenvars){
          index<-(1+(k-1))+((j-1)*nContCDSgenvars)
          set.seed(newseedstart+index)
          contCDS[,index]<-complement(combclusts[[i]][,j],CDSrho)
        }
      }; rm(j,k)
      catCDS<-matrix(0,nrow(grc.clusts$datList[[i]]),nCatCDSgenvars*nCatCDSrootvars)
      newseedstart<-newseedstart*nCatCDSrootvars*nCatCDSgenvars
      for(j in (ncontvars+1):(nCatCDSrootvars+ncontvars)){
        for(k in 1:nCatCDSgenvars){
          index<-(1+(k-1))+((j-(1+ncontvars))*nCatCDSgenvars)
          set.seed(newseedstart+index)
          catCDS[,index]<-complement(combclusts[[i]][,j],CDSrho)
        }
      }; rm(j,k)
      contCDS<-cbind(contCDS,combclusts[[i]][,(nContCDSrootvars+1):ncontvars])
      catCDS<-cbind(catCDS,combclusts[[i]][,(nCatCDSrootvars+1):ncatvars])
      catCDS<-apply(catCDS,2,function(x) ifelse(x>quantile(x,probs=catq),1,0))
      combclusts[[i]]<-as.data.frame(cbind(contCDS,catCDS))
      for(k in c((ncol(contCDS)+1):ncol(combclusts[[i]]))){
        combclusts[[i]][,k]<-as.factor(combclusts[[i]][,k])
        levels(combclusts[[i]][,k])<-paste0("x",k,"=",0:1)
      }; rm(k)
      names(combclusts[[i]])<-paste0("x",1:ncol(combclusts[[i]]))
      combclusts[[i]]$DiseaseState<-as.factor(grc.clusts$memList[[i]])
      levels(combclusts[[i]]$DiseaseState)<-paste0("D",levels(combclusts[[i]]$DiseaseState))
      combclusts[[i]]$Cohort<-as.factor(grc.cohorts$memList[[i]])
      levels(combclusts[[i]]$Cohort)<-paste0("C",levels(combclusts[[i]]$Cohort))
      combclusts[[i]]$DisCoh<-as.factor(interaction(combclusts[[i]]$DiseaseState,combclusts[[i]]$Cohort))
    }; rm(i)
  } else {
    for(i in 1:length(grc.clusts$datList)){
      combclusts[[i]]<-as.data.frame(grc.clusts$datList[[i]]+grc.cohorts$datList[[i]])
      names(combclusts[[i]])<-paste0("x",1:ncol(combclusts[[i]]))
      if(!is.null(missindex)){
        nonadf<-combclusts[[i]]
        library(FactoMineR)
        if(is.null(missseed)) missseed<-sample(1:1E6,1)
        missseed<-missseed+i
        if(comiss){
          if(misstype=="MCAR"){
            set.seed(missseed)
            combclusts[[i]][
              sample(1:nrow(combclusts[[i]]),
                     size=floor(ratiomiss*nrow(combclusts[[i]])),replace=F),missindex]<-NA
          } else if(misstype=="MAR"){
            newmissratio<-ratiomiss*1.5
            nadriver<-combclusts[[i]][,grep("x",names(combclusts[[i]]))][,-missindex]
            nadriverclass<-sapply(nadriver,class)
            nadriverclass<-ifelse(nadriverclass=="continuous","s","n")
            napca<-PCA(nadriver,scale.unit=T,ncp=5,graph=F)
            #napca<-MFA(nadriver,group=rep(1,ncol(nadriver)),type=nadriverclass,ncp=5,graph=F)
            nadriver<-napca$ind$coord[,1]
            #nadriver<-nadriver[,sapply(nadriver,is.numeric)][,1]
            #missprobpred<-1/(1+exp(-1*(-3+nadriver*0.2)))
            set.seed(missseed)
            missppts<-sample(which(nadriver>=quantile(nadriver,probs=(1-newmissratio))),
                             size=ratiomiss*nrow(combclusts[[i]]),replace=F)
            combclusts[[i]][missppts,missindex]<-NA
          } else if(misstype=="MNAR"){
            newmissratio<-ratiomiss*1.5
            nadriver<-combclusts[[i]][,grep("x",names(combclusts[[i]]))][,missindex]
            napca<-PCA(nadriver,scale.unit=T,ncp=5,graph=F)
            nadriver<-napca$ind$coord[,1]
            # nadriver<-combclusts[[i]][,grep("x",names(combclusts[[i]]))][,missindex]
            # nadriver<-nadriver[,sapply(nadriver,is.numeric)][,1]
            set.seed(missseed)
            missppts<-sample(which(nadriver>=quantile(nadriver,probs=(1-newmissratio))),
                             size=ratiomiss*nrow(combclusts[[i]]),replace=F)
            combclusts[[i]][missppts,missindex]<-NA
          } else {stop("misstype must be one of 'MCAR', 'MAR', or 'MNAR'")}
        } else {
          if(misstype=="MCAR"){
            for(j in missindex){
              missseed<-missseed+j
              set.seed(missseed)
              combclusts[[i]][
                sample(1:nrow(combclusts[[i]]),
                       size=floor(ratiomiss*nrow(combclusts[[i]])),replace=F),j]<-NA}
          } else if(misstype=="MAR"){
            newmissratio<-ratiomiss*1.5
            nadriver<-combclusts[[i]][,grep("x",names(combclusts[[i]]))][,-missindex]
            napca<-PCA(nadriver,graph=F)
            nadriver<-napca$ind$coord[,1]
            # nadriver<-combclusts[[i]][,-missindex]
            # nadriver<-nadriver[,sapply(nadriver,is.numeric)][,1]
            for(j in missindex){
              missseed<-missseed+j
              set.seed(missseed)
              missppts<-sample(which(nadriver>=quantile(nadriver,probs=(1-newmissratio))),
                               size=ratiomiss*nrow(combclusts[[i]]),replace=F)
              combclusts[[i]][missppts,j]<-NA
            }
          } else if(misstype=="MNAR"){
            newmissratio<-ratiomiss*1.5
            nadriver<-combclusts[[i]][,grep("x",names(combclusts[[i]]))][,missindex]
            napca<-PCA(nadriver,graph=F)
            nadriver<-napca$ind$coord[,1]
            # nadriver<-combclusts[[i]][,missindex]
            # nadriver<-nadriver[,sapply(nadriver,is.numeric)][,1]
            for(j in missindex){
              # if(j==min(missindex)) driverindex<-j-1 else driverindex<-max(missindex)
              # nadriver<-combclusts[[i]][,paste0("x",driverindex)]
              missseed<-missseed+j
              set.seed(missseed)
              missppts<-sample(which(nadriver>=quantile(nadriver,probs=(1-newmissratio))),
                               size=ratiomiss*nrow(combclusts[[i]]),replace=F)
              combclusts[[i]][missppts,j]<-NA
            }
          } else {stop("misstype must be one of 'MCAR', 'MAR', or 'MNAR'")}
        }
        catcols<-(((nSignal+nNoise)-ncatvars)+1):(nSignal+nNoise)
        for(k in catcols){
          nonabin<-ifelse(nonadf[,k]>quantile(nonadf[,k],probs=catq),1,0)
          combclusts[[i]][which(!is.na(combclusts[[i]][,k])),k]<-nonabin[which(!is.na(combclusts[[i]][,k]))]
          combclusts[[i]][,k]<-as.factor(combclusts[[i]][,k])
          levels(combclusts[[i]][,k])<-paste(names(combclusts[[i]])[k],levels(combclusts[[i]][,k]),sep="=")
        };rm(k)
      } else {
        catcols<-(((nSignal+nNoise)-ncatvars)+1):(nSignal+nNoise)
        for(k in catcols){
          combclusts[[i]][,k]<-as.factor(ifelse(combclusts[[i]][,k]>quantile(combclusts[[i]][,k],probs=catq),1,0))
          levels(combclusts[[i]][,k])<-paste(names(combclusts[[i]])[k],levels(combclusts[[i]][,k]),sep="=")
        };rm(k)
      }

      combclusts[[i]]$DiseaseState<-as.factor(grc.clusts$memList[[i]])
      levels(combclusts[[i]]$DiseaseState)<-paste0("D",levels(combclusts[[i]]$DiseaseState))
      combclusts[[i]]$Cohort<-as.factor(grc.cohorts$memList[[i]])
      levels(combclusts[[i]]$Cohort)<-paste0("C",levels(combclusts[[i]]$Cohort))
      combclusts[[i]]$DisCoh<-as.factor(interaction(combclusts[[i]]$DiseaseState,combclusts[[i]]$Cohort))
    }; rm(i)
  }
  return(list(DataList=combclusts,args=cl))
}
